{
 "title": "Druid Realtime Task",
 "tags": [ "druid" ],
 "time": { "from": "now-15m", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "source",
    "query": "kaijianding-opentsdb-druid-datasource"
   },
   { "name": "cluster", "query": "docker" },
   {
    "name": "DataSource",
    "query": "tag_values(jvm.mem.used, dataSource, service=druid.peon, clusterName=$cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "数据源详情",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "segment个数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "不含副本",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "segment.count",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "service": "druid.coordinator" }
      },
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "含副本",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "segment.count",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "segment大小",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "不含副本",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "segment.size",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "service": "druid.coordinator" }
      },
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "含副本",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "segment.used",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Task数量",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "count",
       "alias": "$tag_dataSource",
       "currentTagKey": "host",
       "downsampleAggregator": "count",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "memKind": "heap", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "总行数(需要自己改参数)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregators": [
        { "fieldName": "count", "name": "count", "type": "longSum" }
       ],
       "currentAggregator": { "type": "count" },
       "currentFilter": { "type": "selector" },
       "currentPostAggregator": { "fn": "+", "type": "arithmetic" },
       "currentSelect": { "dimension": "", "metric": "" },
       "customGranularity": "minute",
       "druidDS": "new_ds_for_test",
       "limit": 5
      }
     ]
    }
   ]
  },
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "success",
       "currentTagKey": "dataSource",
       "currentTagValue": "$DataSource",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.time",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "service": "druid.broker", "success": "true" }
      },
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "fail",
       "currentTagKey": "dataSource",
       "currentTagValue": "$DataSource",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.time",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "service": "druid.broker", "success": "false" },
       "tenant": "default"
      },
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "all",
       "currentTagKey": "dataSource",
       "currentTagValue": "$DataSource",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.time",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "Realtime Query QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_type",
       "currentTagKey": "type",
       "currentTagValue": "*",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.time",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "service": "druid.peon", "type": "*" }
      }
     ]
    },
    {
     "title": "Historical Query QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "type",
       "currentTagValue": "*",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.time",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Query平均耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_type-$tag_success",
       "currentTagKey": "type",
       "currentTagValue": "*",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.time",
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "$DataSource",
        "service": "druid.broker",
        "success": "*",
        "type": "*"
       }
      }
     ]
    },
    {
     "title": "Realtime Query最大耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_type-$tag_success",
       "currentTagKey": "type",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.time",
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "$DataSource",
        "service": "druid.peon",
        "success": "*",
        "type": "*"
       }
      }
     ]
    },
    {
     "title": "Historical Query最大耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_type-$tag_success",
       "currentTagKey": "type",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.time",
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "$DataSource",
        "service": "druid.historical",
        "success": "*",
        "type": "*"
       }
      }
     ]
    },
    {
     "title": "Query Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_type",
       "currentTagKey": "dataSource",
       "currentTagValue": "$DataSource",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.bytes",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "service": "druid.broker", "type": "*" }
      }
     ]
    },
    {
     "title": "Scan Pending",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "segment.scan.pending",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "Historical Scan Pending",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "segment.scan.pending",
       "tags": { "clusterName": "$cluster", "host": "*", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Realtime Query Fail QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_type",
       "currentTagKey": "type",
       "currentTagValue": "*",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.time",
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "$DataSource",
        "service": "druid.peon",
        "success": "false",
        "type": "*"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Realtime Task详情",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events Per Sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "processed",
       "currentTagKey": "dataSource",
       "currentTagValue": "$DataSource",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "ingest.events.processed",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource" }
      },
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "thrownAway",
       "currentTagKey": "clusterName",
       "currentTagValue": "$cluster",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.events.thrownAway",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource" },
       "tenant": "default"
      },
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "unparseable",
       "currentTagKey": "clusterName",
       "currentTagValue": "$cluster",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.events.unparseable",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource" },
       "tenant": "default"
      }
     ]
    },
    {
     "title": "Task Processed Events Per Sec TopN",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "ingest.events.processed",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      }
     ]
    },
    {
     "title": "消息延迟",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.events.messageGap",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      }
     ]
    },
    {
     "title": "Task Thrown Events Per Sec TopN",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.events.thrownAway",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      }
     ]
    },
    {
     "title": "Kafka or ddmq lag",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "kafka",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.kafka.lag",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      },
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "ddmq",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.ddmq.lag",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource" }
      }
     ]
    },
    {
     "title": "数据源延迟",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.events.sourceGap",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      }
     ]
    },
    {
     "title": "20s内消息最大延迟",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.events.messageMaxGap",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      }
     ]
    },
    {
     "title": "待处理消息条数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.events.available",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      }
     ]
    }
   ]
  },
  {
   "title": "Persists",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "每分钟Persist次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "dataSource",
       "currentTagValue": "$DataSource",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "ingest.persists.count",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      }
     ]
    },
    {
     "title": "Persist记录数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "currentTagKey": "clusterName",
       "currentTagValue": "$cluster",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "downsampleInterval": "30s",
       "granularity": "auto",
       "metric": "ingest.rows.output",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource" }
      }
     ]
    },
    {
     "title": "Persist平均耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.persists.time",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      }
     ]
    },
    {
     "title": "Persist失败次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.persists.failed",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      }
     ]
    },
    {
     "title": "Persist启动延时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.persists.backPressure",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      }
     ]
    }
   ]
  },
  {
   "title": "Merge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Segment个数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.sink.count",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      }
     ]
    },
    {
     "title": "Handoff个数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.handoff.count",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      }
     ]
    },
    {
     "title": "一小时merge耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "downsampleInterval": "3600s",
       "granularity": "60m",
       "metric": "ingest.merge.time",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      }
     ]
    },
    {
     "title": "一小时merge行数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "downsampleInterval": "3600s",
       "granularity": "60m",
       "metric": "ingest.rows.output",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      }
     ]
    },
    {
     "title": "merge耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.merge.time",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      }
     ]
    },
    {
     "title": "merge失败次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.handoff.failed",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*" }
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "堆内内存Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "clusterName",
       "currentTagValue": "$cluster",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "memKind"
       ],
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "$DataSource",
        "host": "*",
        "memKind": "heap",
        "service": "druid.peon"
       }
      }
     ]
    },
    {
     "title": "堆外内存Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "clusterName",
       "currentTagValue": "$cluster",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "memKind"
       ],
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "$DataSource",
        "host": "*",
        "memKind": "nonheap",
        "service": "druid.peon"
       }
      }
     ]
    },
    {
     "title": "YGC次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "gcName",
       "currentTagValue": "G1_Young_Generation",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.count",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "gcName"
       ],
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "$DataSource",
        "gcGen": "young",
        "gcName": "g1",
        "host": "*",
        "service": "druid.peon"
       }
      }
     ]
    },
    {
     "title": "FGC次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "gcName",
       "currentTagValue": "G1_Old_Generation",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.count",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "gcName"
       ],
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "$DataSource",
        "gcGen": "old",
        "gcName": "g1",
        "host": "*",
        "service": "druid.peon"
       }
      }
     ]
    },
    {
     "title": "YGC耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "gcName",
       "currentTagValue": "G1_Young_Generation",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.cpu",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "gcName"
       ],
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "$DataSource",
        "gcGen": "young",
        "gcName": "g1",
        "host": "*",
        "service": "druid.peon"
       }
      }
     ]
    },
    {
     "title": "FGC耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "gcName",
       "currentTagValue": "G1_Old_Generation",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.cpu",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "gcName"
       ],
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "$DataSource",
        "gcGen": "old",
        "gcName": "g1",
        "host": "*",
        "service": "druid.peon"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "平均大小",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "currentTagKey": "dataSource",
       "currentTagValue": "$DataSource",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.cache.total.sizeBytes",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "采样10台大小",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "clusterName",
       "currentTagValue": "$cluster",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.cache.total.sizeBytes",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "cache entry个数",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.cache.total.numEntries",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "cache命中率",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.cache.total.hitRate",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "Cache删除",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "all",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "limit": "all",
       "metric": "query.cache.delta.evictions",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*", "service": "druid.peon" }
      }
     ]
    }
   ]
  },
  {
   "title": "资源消耗",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Task CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "CpuAllocate",
       "currentTagKey": "appName",
       "currentTagValue": "$DataSource",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "$RunningCluster.yarn.nodemanager.containermetrics.CPUAllocated",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "pid"
       ],
       "tags": { "appName": "$DataSource" }
      },
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "CpuUsage",
       "currentTagKey": "appName",
       "currentTagValue": "$DataSource",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "$RunningCluster.yarn.nodemanager.containermetrics.CPUUsage",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "pid"
       ],
       "tags": { "appName": "$DataSource" },
       "tenant": "default"
      }
     ]
    },
    {
     "title": "Task CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "dataSource",
       "currentTagValue": "$DataSource",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.cpu.percent",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*", "service": "druid.peon" }
      },
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "=======CPU Allocate=======",
       "currentTagKey": "appName",
       "currentTagValue": "$DataSource",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "$RunningCluster.yarn.nodemanager.containermetrics.CPUAllocated",
       "tags": { "appName": "$DataSource" }
      }
     ]
    },
    {
     "title": "Task Mem 总量",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "currentTagKey": "clusterName",
       "currentTagValue": "$cluster",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "app.proc.mem_rss_MB",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource" }
      }
     ]
    },
    {
     "title": "Task Mem",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "clusterName",
       "currentTagValue": "$cluster",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.max",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "Task Mem",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Allocate",
       "currentTagKey": "appName",
       "currentTagValue": "$DataSource",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "$RunningCluster.yarn.nodemanager.containermetrics.MemAllocated",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "pid"
       ],
       "tags": { "appName": "$DataSource", "clusterName": "$cluster" }
      },
      {
       "aggregator": "max",
       "alias": "Usage",
       "currentTagKey": "appName",
       "currentTagValue": "$DataSource",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "$RunningCluster.yarn.nodemanager.containermetrics.MemUsage",
       "tags": { "appName": "$DataSource", "clusterName": "$cluster" }
      }
     ]
    }
   ]
  }
 ]
}