{
 "title": "Druid Realtime Jobs",
 "tags": [ "druid" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source",
    "query": "kaijianding-opentsdb-druid-datasource"
   },
   { "name": "cluster", "query": "docker" }
  ]
 },
 "panels": [
  {
   "title": "Task汇总",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "count",
       "alias": "$tag_dataSource",
       "currentTagKey": "dataSource",
       "currentTagValue": "*",
       "downsampleAggregator": "count",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "ingest.events.messageGap",
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "Full GC次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_dataSource",
       "currentTagKey": "gcName",
       "currentTagValue": "G1_Old_Generation",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.count",
       "tags": { "clusterName": "$cluster", "dataSource": "*", "gcGen": "old", "service": "druid.peon" }
      }
     ]
    }
   ]
  },
  { "title": "Build", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Message Gap Top 20",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "max",
     "alias": "$tag_dataSource",
     "currentTagKey": "cluster",
     "currentTagValue": "$cluster",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "granularity": "1m",
     "metric": "ingest.events.messageGap",
     "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.peon" }
    }
   ]
  },
  {
   "title": "kafka or ddmq lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": "20",
     "aggregator": "max",
     "alias": "$tag_dataSource",
     "currentTagKey": "cluster",
     "currentTagValue": "$cluster",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "granularity": "1m",
     "limit": "avg:top:20",
     "metric": "ingest.kafka.lag",
     "tags": { "clusterName": "$cluster", "dataSource": "*" }
    },
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": "20",
     "aggregator": "max",
     "alias": "$tag_dataSource",
     "currentTagKey": "cluster",
     "currentTagValue": "$cluster",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "granularity": "1m",
     "limit": "avg:top:20",
     "metric": "ingest.ddmq.lag",
     "tags": { "clusterName": "$cluster", "dataSource": "*" }
    }
   ]
  },
  {
   "title": "内存segment个数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "max",
     "alias": "$tag_dataSource",
     "currentTagKey": "cluster",
     "currentTagValue": "$cluster",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "granularity": "1m",
     "metric": "ingest.sink.count",
     "tags": { "clusterName": "$cluster", "dataSource": "*" }
    }
   ]
  },
  {
   "title": "实时build成功量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "alias": "$tag_dataSource",
     "currentTagKey": "dataSource",
     "currentTagValue": "*",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "1m",
     "metric": "ingest.events.processed",
     "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.peon" }
    }
   ]
  },
  {
   "title": "CPU使用最高",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "max",
     "alias": "$tag_dataSource",
     "currentTagKey": "type",
     "currentTagValue": "*",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "auto",
     "metric": "jvm.cpu.percent",
     "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.peon" }
    }
   ]
  },
  {
   "title": "Persist失败",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "alias": "$tag_dataSource",
     "currentTagKey": "type",
     "currentTagValue": "*",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "auto",
     "metric": "ingest.persists.failed",
     "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.peon" }
    }
   ]
  },
  {
   "title": "实时build丢弃量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "alias": "$tag_dataSource",
     "currentTagKey": "dataSource",
     "currentTagValue": "*",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "1m",
     "metric": "ingest.events.thrownAway",
     "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.peon" }
    }
   ]
  },
  {
   "title": "实时build重复量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "alias": "$tag_dataSource",
     "currentTagKey": "dataSource",
     "currentTagValue": "*",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "auto",
     "metric": "ingest.events.duplicate",
     "tags": { "clusterName": "$cluster", "service": "druid.peon" }
    }
   ]
  },
  {
   "title": "Merge失败",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "alias": "$tag_dataSource",
     "currentTagKey": "type",
     "currentTagValue": "*",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "auto",
     "metric": "ingest.handoff.failed",
     "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.peon" }
    }
   ]
  },
  {
   "title": "查询",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "broker查询耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_dataSource",
       "currentTagKey": "dataSource",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.time",
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "broker查询成功qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_dataSource",
       "currentTagKey": "success",
       "currentTagValue": "true",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.time",
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "broker查询失败qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_dataSource-$tag_type",
       "currentTagKey": "type",
       "currentTagValue": "*",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.time",
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.broker", "success": "false" }
      }
     ]
    },
    {
     "title": "historical full gc时间",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "gcName",
       "currentTagValue": "G1_Old_Generation",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "jvm.gc.cpu",
       "tags": {
        "clusterName": "$cluster",
        "gcGen": "old",
        "gcName": "g1",
        "host": "*",
        "service": "druid.historical"
       }
      }
     ]
    },
    {
     "title": "Young GC次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_dataSource",
       "currentTagKey": "dataSource",
       "currentTagValue": "*",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.count",
       "tags": { "clusterName": "$cluster", "dataSource": "*", "gcGen": "young", "service": "druid.peon" }
      }
     ]
    }
   ]
  }
 ]
}