{
 "title": "Druid Statistics",
 "tags": [ "druid" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source",
    "query": "kaijianding-opentsdb-druid-datasource"
   },
   { "name": "cluster", "query": "docker" }
  ]
 },
 "panels": [
  {
   "title": "数据源个数",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "count",
     "currentTagKey": "dataSource",
     "currentTagValue": "*",
     "downsampleAggregator": "original_count",
     "downsampleFillPolicy": "none",
     "granularity": "20s",
     "metric": "segment.count",
     "tags": { "clusterName": "$cluster", "service": "druid.coordinator" }
    }
   ]
  },
  {
   "title": "Task个数",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "count",
     "currentTagKey": "dataSource",
     "currentTagValue": "*",
     "downsampleAggregator": "count",
     "downsampleFillPolicy": "none",
     "granularity": "20s",
     "metric": "ingest.events.messageGap",
     "tags": { "clusterName": "$cluster", "service": "druid.peon" }
    }
   ]
  },
  {
   "title": "最近24小时查询总次数",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "alias": "总次数",
     "currentFilterType": "literal_or",
     "currentTagKey": "gcName",
     "currentTagValue": "G1_Old_Generation",
     "downsampleAggregator": "original_count",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "segmentMetadata",
       "groupBy": false,
       "tagk": "type",
       "type": "not_literal_or"
      },
      {
       "filter": "druid.broker",
       "groupBy": false,
       "tagk": "service",
       "type": "literal_or"
      },
      {
       "filter": "timeBoundary",
       "groupBy": false,
       "tagk": "type",
       "type": "not_literal_or"
      },
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "clusterName",
       "type": "literal_or"
      }
     ],
     "granularity": "60m",
     "metric": "query.time"
    }
   ]
  },
  {
   "title": "最近24小时查询总次数排行",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": "15",
     "aggregator": "sum",
     "alias": "$tag_dataSource",
     "currentFilterType": "literal_or",
     "currentTagKey": "gcName",
     "currentTagValue": "G1_Old_Generation",
     "downsampleAggregator": "original_count",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "segmentMetadata",
       "groupBy": false,
       "tagk": "type",
       "type": "not_literal_or"
      },
      {
       "filter": "*",
       "groupBy": true,
       "tagk": "dataSource",
       "type": "wildcard"
      },
      {
       "filter": "druid.broker",
       "groupBy": false,
       "tagk": "service",
       "type": "literal_or"
      },
      {
       "filter": "timeBoundary",
       "groupBy": false,
       "tagk": "type",
       "type": "not_literal_or"
      },
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "clusterName",
       "type": "literal_or"
      }
     ],
     "granularity": "60m",
     "limit": "avg:top:15",
     "metric": "query.time",
     "tags": { "service": "druid.broker" }
    }
   ]
  },
  {
   "title": "历史节点容量",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "currentTagKey": "dataSource",
     "currentTagValue": "*",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "20s",
     "metric": "segment.max",
     "tags": { "clusterName": "$cluster", "service": "druid.historical" }
    }
   ]
  },
  {
   "title": "历史节点使用量",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "currentTagKey": "dataSource",
     "currentTagValue": "*",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "20s",
     "metric": "segment.used",
     "tags": { "clusterName": "$cluster", "service": "druid.historical" }
    }
   ]
  },
  {
   "title": "24小时平均1分钟内p95耗时",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "p95",
     "currentFilterType": "literal_or",
     "currentTagKey": "dataSource",
     "currentTagValue": "*",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "segmentMetadata",
       "groupBy": false,
       "tagk": "type",
       "type": "not_literal_or"
      },
      {
       "filter": "druid.broker",
       "groupBy": false,
       "tagk": "service",
       "type": "literal_or"
      },
      {
       "filter": "timeBoundary",
       "groupBy": false,
       "tagk": "type",
       "type": "not_literal_or"
      },
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "clusterName",
       "type": "literal_or"
      }
     ],
     "granularity": "1m",
     "metric": "query.time"
    }
   ]
  },
  {
   "title": "7天前数据源存储量排行(含2副本)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "alias": "$tag_dataSource",
     "currentTagKey": "dataSource",
     "currentTagValue": "*",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "20s",
     "metric": "segment.used",
     "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.historical" }
    }
   ]
  },
  {
   "title": "数据源存储量排行(含2副本)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "alias": "$tag_dataSource",
     "currentTagKey": "dataSource",
     "currentTagValue": "*",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "20s",
     "metric": "segment.used",
     "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.historical" }
    }
   ]
  }
 ]
}