{
 "title": "Druid Historical",
 "tags": [ "druid" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source",
    "query": "kaijianding-opentsdb-druid-datasource"
   },
   { "name": "cluster", "query": "docker" },
   {
    "name": "host",
    "query": "tag_values(jvm.mem.used, host, service=druid.historical,clusterName=$cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "存储",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "存储量",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "20s",
       "metric": "segment.used",
       "tags": { "clusterName": "$cluster", "host": "$host", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "存储量分布",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_dataSource",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "segment.used",
       "tags": { "clusterName": "$cluster", "dataSource": "*", "host": "$host", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "segment个数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "all",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "20s",
       "limit": "all",
       "metric": "segment.count",
       "tags": { "clusterName": "$cluster", "host": "$host", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "segment个数分布",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_dataSource",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "segment.count",
       "tags": { "clusterName": "$cluster", "dataSource": "*", "host": "$host", "service": "druid.historical" }
      }
     ]
    }
   ]
  },
  {
   "title": "查询",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query最大耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "all",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "最大耗时",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "limit": "all",
       "metric": "query.time",
       "tags": { "clusterName": "$cluster", "host": "$host", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Query Qps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": "20",
       "aggregator": "sum",
       "alias": "$tag_type",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "limit": "avg:top:20",
       "metric": "query.time",
       "tags": { "clusterName": "$cluster", "host": "$host", "service": "druid.historical", "type": "*" }
      }
     ]
    },
    {
     "title": "Fail Query Qps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "all",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_dataSource",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "limit": "all",
       "metric": "query.time",
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "*",
        "host": "$host",
        "service": "druid.historical",
        "success": "false"
       }
      }
     ]
    },
    {
     "title": "Query最大耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_dataSource-$tag_type",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "limit": "avg:top:10",
       "metric": "query.time",
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "*",
        "host": "$host",
        "service": "druid.historical",
        "type": "*"
       }
      }
     ]
    },
    {
     "title": "Query Qps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": "20",
       "aggregator": "sum",
       "alias": "$tag_dataSource-$tag_type",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "limit": "avg:top:20",
       "metric": "query.time",
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "*",
        "host": "$host",
        "service": "druid.historical",
        "type": "*"
       }
      }
     ]
    },
    {
     "title": "Scan Pending",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "all",
       "aggregateNumber": 10,
       "aggregator": "max",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "limit": "all",
       "metric": "segment.scan.pending",
       "tags": { "clusterName": "$cluster", "host": "$host", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Query平均耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_dataSource-$tag_type",
       "currentFilterType": "literal_or",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "limit": "avg:top:10",
       "metric": "query.time",
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "*",
        "host": "$host",
        "service": "druid.historical",
        "type": "*"
       }
      }
     ]
    },
    {
     "title": "Query Qps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": "20",
       "aggregator": "sum",
       "alias": "$tag_dataSource-$tag_type",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "limit": "avg:top:20",
       "metric": "query.time",
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "*",
        "host": "$host",
        "service": "druid.historical",
        "type": "*"
       }
      }
     ]
    },
    {
     "title": "Jetty Open Connection",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "all",
       "aggregateNumber": 10,
       "aggregator": "max",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "limit": "all",
       "metric": "jetty.numOpenConnections",
       "tags": { "clusterName": "$cluster", "host": "$host", "service": "druid.historical" }
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache大小",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "all",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "limit": "all",
       "metric": "query.cache.total.sizeBytes",
       "tags": { "clusterName": "$cluster", "host": "$host", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Cache命中率",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "all",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "limit": "all",
       "metric": "query.cache.total.hitRate",
       "tags": { "clusterName": "$cluster", "host": "$host", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Cache Entry个数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "all",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "limit": "all",
       "metric": "query.cache.total.numEntries",
       "tags": { "clusterName": "$cluster", "host": "$host", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Cache删除",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "all",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "limit": "all",
       "metric": "query.cache.delta.evictions",
       "tags": { "clusterName": "$cluster", "host": "$host", "service": "druid.historical" }
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "内存",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "使用",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.used",
       "tags": { "clusterName": "$cluster", "host": "$host", "memKind": "heap", "service": "druid.historical" }
      },
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "上限",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.max",
       "tags": { "clusterName": "$cluster", "host": "$host", "memKind": "heap", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "young gc耗时",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "耗时",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.cpu",
       "tags": { "clusterName": "$cluster", "gcGen": "young", "host": "$host", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "full gc耗时",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.cpu",
       "tags": { "clusterName": "$cluster", "gcGen": "old", "host": "$host", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.cpu.percent",
       "tags": { "clusterName": "$cluster", "host": "$host", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Query CPU时间",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_dataSource",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.cpu.time",
       "tags": { "clusterName": "$cluster", "dataSource": "*", "host": "$host", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Query总耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_dataSource",
       "currentFilterType": "literal_or",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "limit": "avg:top:10",
       "metric": "query.time",
       "tags": { "clusterName": "$cluster", "dataSource": "*", "host": "$host", "service": "druid.historical" }
      }
     ]
    }
   ]
  }
 ]
}