{
 "title": "Druid Overall",
 "tags": [ "druid" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source",
    "query": "kaijianding-opentsdb-druid-datasource"
   },
   { "name": "cluster", "query": "docker" }
  ]
 },
 "panels": [
  {
   "title": "summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Broker数",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "count",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.max",
       "tagKeys": [
        "host",
        "cluster",
        "db",
        "memKind"
       ],
       "tags": { "clusterName": "$cluster", "memKind": "heap", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "Historical数",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "count",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.max",
       "tagKeys": [
        "host",
        "cluster",
        "memKind"
       ],
       "tags": { "clusterName": "$cluster", "memKind": "heap", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "总数据量",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "currentFilterKey": "cluster",
       "currentFilterType": "literal_or",
       "currentFilterValue": "$cluster",
       "currentTagKey": "shard",
       "currentTagValue": "$shard",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "20s",
       "metric": "segment.size",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.coordinator" }
      }
     ]
    },
    {
     "title": "Segment总数",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "currentFilterKey": "dataSource",
       "currentFilterType": "wildcard",
       "currentFilterValue": "opentsdb_*",
       "currentTagKey": "shard",
       "currentTagValue": "$shard",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "segment.count",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.coordinator" }
      }
     ]
    },
    {
     "title": "Segment实际加载数",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "currentTagKey": "tier",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "20s",
       "metric": "segment.count",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "priority",
        "tier"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Segment实际加载大小",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "currentTagKey": "tier",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "20s",
       "metric": "segment.used",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "priority",
        "tier"
       ],
       "tags": { "clusterName": "$cluster" }
      }
     ]
    }
   ]
  },
  {
   "title": "Broker Query指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_dataSource-$tag_type",
       "currentFilterKey": "db",
       "currentFilterType": "literal_or",
       "currentFilterValue": "$db",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.time",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "db",
        "success",
        "type"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.broker", "type": "*" }
      }
     ]
    },
    {
     "title": "Query平均耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_dataSource-$tag_type",
       "currentFilterType": "literal_or",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$cluster",
         "groupBy": false,
         "tagk": "clusterName",
         "type": "literal_or"
        },
        {
         "filter": "druid.broker",
         "groupBy": false,
         "tagk": "service",
         "type": "literal_or"
        },
        {
         "filter": "*",
         "groupBy": true,
         "tagk": "dataSource",
         "type": "wildcard"
        },
        {
         "filter": "segmentMetadata",
         "groupBy": false,
         "tagk": "type",
         "type": "not_literal_or"
        },
        {
         "filter": "timeBoundary",
         "groupBy": true,
         "tagk": "type",
         "type": "not_literal_or"
        }
       ],
       "granularity": "auto",
       "metric": "query.time",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "db",
        "success",
        "type"
       ]
      }
     ]
    },
    {
     "title": "Broker Query Qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentFilterType": "literal_or",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$cluster",
         "groupBy": false,
         "tagk": "clusterName",
         "type": "literal_or"
        },
        {
         "filter": "druid.broker",
         "groupBy": false,
         "tagk": "service",
         "type": "literal_or"
        },
        {
         "filter": "segmentMetadata",
         "groupBy": false,
         "tagk": "type",
         "type": "not_literal_or"
        },
        {
         "filter": "timeBoundary",
         "groupBy": false,
         "tagk": "type",
         "type": "not_literal_or"
        },
        {
         "filter": "*",
         "groupBy": true,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "granularity": "1m",
       "metric": "query.time",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "db",
        "success",
        "type"
       ]
      }
     ]
    },
    {
     "title": "Query Qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_dataSource",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.time",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "db",
        "success",
        "type"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "Fail Query Qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_dataSource",
       "currentTagKey": "dataSource",
       "currentTagValue": "*",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.time",
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.broker", "success": "false" }
      }
     ]
    },
    {
     "title": "Query最大耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_dataSource-$tag_type",
       "currentFilterType": "literal_or",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.time",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "db",
        "success",
        "type"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.broker", "type": "*" }
      }
     ]
    },
    {
     "title": "Query Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_dataSource",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.bytes",
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "Broker上Query CPU时间",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_dataSource",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.cpu.time",
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.broker" }
      }
     ]
    }
   ]
  },
  {
   "title": "详细Query指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Realtime Query Qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_dataSource-$tag_type",
       "currentTagKey": "dataSource",
       "currentTagValue": "*",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.time",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "success",
        "type"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.peon", "type": "*" }
      }
     ]
    },
    {
     "title": "Historical Query Qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_dataSource-$tag_type",
       "currentTagKey": "dataSource",
       "currentTagValue": "*",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.time",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "success",
        "type"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.historical", "type": "*" }
      }
     ]
    },
    {
     "title": "Realtime Query平均耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_dataSource-$tag_type",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.time",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "success",
        "type"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.peon", "type": "*" }
      }
     ]
    },
    {
     "title": "Historical Query平均耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_dataSource-$tag_type",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.time",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "success",
        "type"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.historical", "type": "*" }
      }
     ]
    },
    {
     "title": "Realtime Query最大耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_dataSource-$tag_type",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.time",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "success",
        "type"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.peon", "type": "*" }
      }
     ]
    },
    {
     "title": "Historical Query最大耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_dataSource-$tag_type",
       "currentTagKey": "db",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.time",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "success",
        "type"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.historical", "type": "*" }
      }
     ]
    },
    {
     "title": "Realtime Fail qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_dataSource",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.time",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "success",
        "type"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.peon", "success": "false" }
      }
     ]
    },
    {
     "title": "Historical Fail qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "success",
       "downsampleAggregator": "original_count",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.time",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "success",
        "type"
       ],
       "tags": { "clusterName": "$cluster", "host": "*", "service": "druid.historical", "success": "false" }
      }
     ]
    },
    {
     "title": "Realtime Scan Pending",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_dataSource",
       "currentTagKey": "dataSource",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "segment.scan.pending",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "success",
        "type"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "Historical Scan Pending",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_host",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "segment.scan.pending",
       "tagKeys": [
        "host",
        "cluster"
       ],
       "tags": { "clusterName": "$cluster", "host": "*", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Jetty Open Connection",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_dataSource",
       "currentTagKey": "dataSource",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jetty.numOpenConnections",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "success",
        "type"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "Jetty Open Connection",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "$tag_host",
       "currentTagKey": "dataSource",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jetty.numOpenConnections",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "success",
        "type"
       ],
       "tags": { "clusterName": "$cluster", "host": "*", "service": "druid.historical" }
      }
     ]
    }
   ]
  },
  {
   "title": "JVM概况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Used TopN (Broker)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "cluster",
        "db",
        "memKind"
       ],
       "tags": { "clusterName": "$cluster", "host": "*", "memKind": "heap", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "GC耗时 Top (Broker)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.cpu",
       "tagKeys": [
        "host",
        "cluster",
        "db",
        "gcName"
       ],
       "tags": { "clusterName": "$cluster", "gcName": "g1", "host": "*", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "JVM Used TopN (Historical)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "cluster",
        "memKind"
       ],
       "tags": { "clusterName": "$cluster", "host": "*", "memKind": "heap", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "GC耗时 Top (Historical)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "gcName",
       "currentTagValue": "G1_Old_Generation",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.cpu",
       "tagKeys": [
        "host",
        "cluster",
        "gcName"
       ],
       "tags": { "clusterName": "$cluster", "gcName": "g1", "host": "*", "service": "druid.historical" }
      }
     ]
    }
   ]
  },
  {
   "title": "Cache概况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Historical Cache总平均大小",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.cache.total.sizeBytes",
       "tagKeys": [
        "host",
        "cluster"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Historical Cache全局命中率",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.cache.total.hitRate",
       "tagKeys": [
        "host",
        "cluster"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "全局cache命中率 （采样20台）",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "shuffle",
       "aggregateNumber": "20",
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "limit": "avg:sample:20",
       "metric": "query.cache.total.hitRate",
       "tagKeys": [
        "host",
        "cluster"
       ],
       "tags": { "clusterName": "$cluster", "host": "*", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "上个采样周期内Cache删除",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": "20",
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "limit": "avg:top:20",
       "metric": "query.cache.delta.evictions",
       "tagKeys": [
        "host",
        "cluster"
       ],
       "tags": { "clusterName": "$cluster", "host": "*", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Cache大小（采样20台）",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "shuffle",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "limit": "avg:sample:10",
       "metric": "query.cache.total.sizeBytes",
       "tagKeys": [
        "host",
        "cluster"
       ],
       "tags": { "clusterName": "$cluster", "host": "*", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Cache Entry数量（采样20台）",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.cache.total.numEntries",
       "tagKeys": [
        "host",
        "cluster"
       ],
       "tags": { "clusterName": "$cluster", "host": "*", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Realtime Cach平均大小",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_dataSource",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "query.cache.total.sizeBytes",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "Realtime Cache命中率",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "shuffle",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_dataSource",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "limit": "avg:sample:10",
       "metric": "query.cache.total.hitRate",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "Broker Cache平均大小",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.cache.total.sizeBytes",
       "tagKeys": [
        "host",
        "cluster"
       ],
       "tags": { "clusterName": "$cluster", "host": "*", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "Broker Cache平均命中率",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.cache.total.hitRate",
       "tagKeys": [
        "host",
        "cluster"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "Broker Cache命中次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.cache.total.hits",
       "tagKeys": [
        "host",
        "cluster"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "Broker Cache出错次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "query.cache.total.errors",
       "tagKeys": [
        "host",
        "cluster"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.broker" }
      }
     ]
    }
   ]
  },
  {
   "title": "historical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "实际加载segment数 Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "20s",
       "metric": "segment.count",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "priority",
        "tier"
       ],
       "tags": { "clusterName": "$cluster", "host": "*", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Historical Query最大耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest max",
       "aggregateNumber": "20",
       "aggregator": "max",
       "alias": "$tag_host-$tag_dataSource-$tag_type",
       "currentFilterType": "literal_or",
       "currentTagKey": "dataSource",
       "currentTagValue": "*",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$cluster",
         "groupBy": false,
         "tagk": "clusterName",
         "type": "literal_or"
        },
        {
         "filter": "druid.historical",
         "groupBy": false,
         "tagk": "service",
         "type": "literal_or"
        },
        {
         "filter": "*",
         "groupBy": true,
         "tagk": "dataSource",
         "type": "wildcard"
        },
        {
         "filter": "*",
         "groupBy": true,
         "tagk": "host",
         "type": "wildcard"
        },
        {
         "filter": "segmentMetadata",
         "groupBy": false,
         "tagk": "type",
         "type": "not_literal_or"
        },
        {
         "filter": "timeBoundary",
         "groupBy": false,
         "tagk": "type",
         "type": "not_literal_or"
        },
        {
         "filter": "*",
         "groupBy": true,
         "tagk": "type",
         "type": "wildcard"
        }
       ],
       "granularity": "1m",
       "limit": "max:top:20",
       "metric": "query.time",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "success",
        "type"
       ]
      }
     ]
    },
    {
     "title": "Historical CPU IoWait",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "host",
       "currentTagValue": "*",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "$cluster.system.cpu.iowait",
       "tagKeys": [
        "host",
        "cluster",
        "pid"
       ],
       "tags": { "host": "*" }
      }
     ]
    }
   ]
  },
  {
   "title": "CPU消耗统计(分钟)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Broker平均CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "jvm.cpu.percent",
       "tagKeys": [
        "host",
        "cluster",
        "db",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "Broker CPU Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "jvm.cpu.percent",
       "tagKeys": [
        "host",
        "cluster",
        "db",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "host": "*", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "Broker消耗CPU总量",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "20s",
       "metric": "jvm.cpu.percent",
       "tagKeys": [
        "host",
        "cluster",
        "db",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "Realtime P90 CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "p90",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.cpu.percent",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "Realtime CPU Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_dataSource-$tag_host",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.cpu.percent",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "*", "host": "*", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "Realtime消耗CPU总量",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "jvm.cpu.percent",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "Historical平均CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.cpu.percent",
       "tagKeys": [
        "host",
        "cluster",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Historical CPU Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "limit": "avg:top:10",
       "metric": "jvm.cpu.percent",
       "tagKeys": [
        "host",
        "cluster",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "host": "*", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Historical消耗CPU总量",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "jvm.cpu.percent",
       "tagKeys": [
        "host",
        "cluster",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.historical" }
      }
     ]
    }
   ]
  },
  {
   "title": "内存消耗统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Broker平均内存占用",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "cluster",
        "db",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "memKind": "heap", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "Broker总内存占用",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "downsampleInterval": "20s",
       "granularity": "20s",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "cluster",
        "db",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "Broker内存 Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "cluster",
        "db",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "host": "*", "memKind": "heap", "service": "druid.broker" }
      }
     ]
    },
    {
     "title": "Realtime平均内存占用",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_dataSource",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "*", "memKind": "heap", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "Realtime总内存占用",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "currentFilterType": "literal_or",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "20s",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "Realtime内存 Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "cluster",
        "dataSource",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "host": "*", "memKind": "heap", "service": "druid.peon" }
      }
     ]
    },
    {
     "title": "Historical平均内存占用",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "1m",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "cluster",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "memKind": "heap", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Historical总内存占用",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "20s",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "cluster",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Historical内存 Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "db",
       "currentTagValue": "$db",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "cluster",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "host": "*", "memKind": "heap", "service": "druid.historical" }
      }
     ]
    }
   ]
  }
 ]
}