{
 "title": "Druid Coordinator",
 "tags": [ "druid" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source",
    "query": "kaijianding-opentsdb-druid-datasource"
   },
   { "name": "cluster", "query": "docker" }
  ]
 },
 "panels": [
  {
   "title": "Overlord",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "YGC次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.count",
       "tags": {
        "clusterName": "$cluster",
        "gcGen": "young",
        "gcName": "g1",
        "host": "*",
        "service": "druid.overlord*"
       }
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.cpu.percent",
       "tags": { "clusterName": "$cluster", "host": "*", "service": "druid.overlord*" }
      }
     ]
    }
   ]
  },
  {
   "title": "jvm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "内存",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "上限",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.max",
       "tags": { "clusterName": "$cluster", "memKind": "heap", "service": "druid.coordinator" }
      },
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.used",
       "tags": { "clusterName": "$cluster", "host": "*", "memKind": "heap", "service": "druid.coordinator" }
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.cpu.percent",
       "tags": { "clusterName": "$cluster", "host": "*", "service": "druid.coordinator" }
      }
     ]
    },
    {
     "title": "YGC次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.count",
       "tags": {
        "clusterName": "$cluster",
        "gcGen": "young",
        "gcName": "g1",
        "host": "*",
        "service": "druid.coordinator"
       }
      }
     ]
    },
    {
     "title": "FGC次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.count",
       "tags": {
        "clusterName": "$cluster",
        "gcGen": "old",
        "gcName": "g1",
        "host": "*",
        "service": "druid.coordinator"
       }
      }
     ]
    }
   ]
  },
  { "title": "集群", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "segment个数最多(不含副本)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": "20",
     "aggregator": "sum",
     "alias": "$tag_dataSource",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "auto",
     "limit": "avg:top:20",
     "metric": "segment.count",
     "tags": { "clusterName": "$cluster", "dataSource": "*", "service": "druid.coordinator" }
    }
   ]
  },
  {
   "title": "segment大小最多(不含副本)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": "20",
     "aggregator": "sum",
     "alias": "$tag_dataSource",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "auto",
     "limit": "avg:top:20",
     "metric": "segment.size",
     "tags": { "clusterName": "$cluster", "dataSource": "*" }
    }
   ]
  },
  {
   "title": "historical 存储分布",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregateMethod": "shuffle",
     "aggregateNumber": "20",
     "aggregator": "sum",
     "alias": "$tag_host",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "auto",
     "limit": "avg:sample:20",
     "metric": "segment.used",
     "tags": { "clusterName": "$cluster", "host": "*", "service": "druid.historical" }
    }
   ]
  },
  {
   "title": "Segment个数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "auto",
     "metric": "segment.count",
     "tags": { "clusterName": "$cluster", "service": "druid.coordinator" }
    }
   ]
  },
  {
   "title": "segment实际加载个数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "20s",
     "metric": "segment.count",
     "tags": { "clusterName": "$cluster", "service": "druid.historical" }
    }
   ]
  },
  {
   "title": "assign队列大小",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "auto",
     "metric": "segment.assigned.count",
     "tags": { "clusterName": "$cluster" }
    }
   ]
  },
  {
   "title": "Segment加载队列大小",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "auto",
     "metric": "segment.loadQueue.count",
     "tags": { "clusterName": "$cluster" }
    }
   ]
  },
  {
   "title": "删除segment个数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "auto",
     "metric": "segment.dropped.count",
     "tags": { "clusterName": "$cluster" }
    }
   ]
  },
  {
   "title": "underReplicated个数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "20s",
     "metric": "segment.underReplicated.count",
     "tags": { "clusterName": "$cluster" }
    }
   ]
  },
  {
   "title": "不需要的segment个数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "auto",
     "metric": "segment.unneeded.count",
     "tags": { "clusterName": "$cluster" }
    }
   ]
  },
  {
   "title": "Segment删除队列大小",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "auto",
     "metric": "segment.dropQueue.count",
     "tags": { "clusterName": "$cluster" }
    }
   ]
  },
  {
   "title": "underReplicated的segment个数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "alias": "$tag_dataSource",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "auto",
     "metric": "segment.underReplicated.count",
     "tags": { "clusterName": "$cluster", "dataSource": "*" }
    }
   ]
  },
  {
   "title": "Segment加载队列大小",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregateMethod": "highest average",
     "aggregateNumber": 10,
     "aggregator": "sum",
     "alias": "$tag_server",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "granularity": "auto",
     "metric": "segment.loadQueue.count",
     "tags": { "clusterName": "$cluster", "server": "*" }
    }
   ]
  }
 ]
}