{
 "title": "Druid Batch Task",
 "tags": [ "druid" ],
 "time": { "from": "now-15m", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "source",
    "query": "kaijianding-opentsdb-druid-datasource"
   },
   { "name": "cluster", "query": "docker" },
   {
    "name": "DataSource",
    "query": "tag_values(jvm.mem.used, dataSource, service=druid.batch, clusterName=$cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "数据源详情",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "segment个数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "不含副本",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "segment.count",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "service": "druid.coordinator" }
      },
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "含副本",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "segment.count",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "segment大小",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "不含副本",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "segment.size",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "service": "druid.coordinator" }
      },
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "含副本",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "segment.used",
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "service": "druid.historical" }
      }
     ]
    },
    {
     "title": "Task数量",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "count",
       "alias": "$tag_dataSource",
       "currentTagKey": "host",
       "downsampleAggregator": "count",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "memKind": "heap", "service": "druid.batch" }
      }
     ]
    },
    {
     "title": "总行数(需要自己改参数)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregators": [
        { "fieldName": "count", "name": "count", "type": "longSum" }
       ],
       "currentAggregator": { "type": "count" },
       "currentFilter": { "type": "selector" },
       "currentPostAggregator": { "fn": "+", "type": "arithmetic" },
       "currentSelect": { "dimension": "", "metric": "" },
       "customGranularity": "minute",
       "druidDS": "new_ds_for_test",
       "limit": 5
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "堆内内存Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "clusterName",
       "currentTagValue": "$cluster",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "memKind"
       ],
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "$DataSource",
        "host": "*",
        "memKind": "heap",
        "service": "druid.batch"
       }
      }
     ]
    },
    {
     "title": "堆外内存Top",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "clusterName",
       "currentTagValue": "$cluster",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.used",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "memKind"
       ],
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "$DataSource",
        "host": "*",
        "memKind": "nonheap",
        "service": "druid.batch"
       }
      }
     ]
    },
    {
     "title": "YGC次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "gcName",
       "currentTagValue": "G1_Young_Generation",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.count",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "gcName"
       ],
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "$DataSource",
        "gcGen": "young",
        "gcName": "g1",
        "host": "*",
        "service": "druid.batch"
       }
      }
     ]
    },
    {
     "title": "FGC次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "gcName",
       "currentTagValue": "G1_Old_Generation",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.count",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "gcName"
       ],
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "$DataSource",
        "gcGen": "old",
        "gcName": "g1",
        "host": "*",
        "service": "druid.batch"
       }
      }
     ]
    },
    {
     "title": "YGC耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "gcName",
       "currentTagValue": "G1_Young_Generation",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.cpu",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "gcName"
       ],
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "$DataSource",
        "gcGen": "young",
        "gcName": "g1",
        "host": "*",
        "service": "druid.batch"
       }
      }
     ]
    },
    {
     "title": "FGC耗时",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "gcName",
       "currentTagValue": "G1_Old_Generation",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.gc.cpu",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "gcName"
       ],
       "tags": {
        "clusterName": "$cluster",
        "dataSource": "$DataSource",
        "gcGen": "old",
        "gcName": "g1",
        "host": "*",
        "service": "druid.batch"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "资源消耗",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "avg",
       "alias": "$tag_host",
       "currentTagKey": "dataSource",
       "currentTagValue": "$DataSource",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.cpu.percent",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*", "service": "druid.batch" }
      },
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "max",
       "alias": "=======CPU Allocate=======",
       "currentTagKey": "appName",
       "currentTagValue": "$DataSource",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "$RunningCluster.yarn.nodemanager.containermetrics.CPUAllocated",
       "tags": { "appName": "$DataSource" }
      }
     ]
    },
    {
     "title": "Task Mem",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregateMethod": "highest average",
       "aggregateNumber": 10,
       "aggregator": "sum",
       "alias": "$tag_host",
       "currentTagKey": "clusterName",
       "currentTagValue": "$cluster",
       "downsampleAggregator": "max",
       "downsampleFillPolicy": "none",
       "granularity": "auto",
       "metric": "jvm.mem.max",
       "tagKeys": [
        "host",
        "clusterName",
        "dataSource",
        "pid"
       ],
       "tags": { "clusterName": "$cluster", "dataSource": "$DataSource", "host": "*", "service": "druid.batch" }
      }
     ]
    }
   ]
  }
 ]
}